<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-1DCFOTD" name="features.LoginORMTest" tests="8" failures="1" timestamp="03 Jun 2019 06:32:21 GMT" time="46.792" errors="0">
  <testcase name="TC05_login" time="5.570" classname="features.LoginORMTest"/>
  <testcase name="TC01_login" time="6.096" classname="features.LoginORMTest"/>
  <testcase name="TC08_login" time="7.580" classname="features.LoginORMTest"/>
  <testcase name="TC06_login" time="5.517" classname="features.LoginORMTest"/>
  <testcase name="TC07_login" time="5.862" classname="features.LoginORMTest"/>
  <testcase name="TC03_login" time="5.301" classname="features.LoginORMTest"/>
  <testcase name="TC02_login" time="5.014" classname="features.LoginORMTest"/>
  <testcase name="TC04_login" time="5.852" classname="features.LoginORMTest">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/dashboard&quot;
     but: was &quot;http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/auth/validateCredentials&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/dashboard"
     but: was "http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/auth/validateCredentials"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at pages.login.LoginPage.landingToDashboardPage(LoginPage.java:56)
at features.LoginORMTest.TC04_login(LoginORMTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- TC04_login -->
</testsuite> <!-- features.LoginORMTest -->
